NPC_WEAPONS_MIN_AIM_DELAY_NONE = 0.00
NPC_WEAPONS_MAX_AIM_DELAY_NONE = 0.00
NPC_WEAPONS_MIN_AIM_DELAY_LOW = 0.25
NPC_WEAPONS_MAX_AIM_DELAY_LOW = 0.50
NPC_WEAPONS_MIN_AIM_DELAY_MED = 0.50
NPC_WEAPONS_MAX_AIM_DELAY_MED = 1.00
NPC_WEAPONS_MIN_AIM_DELAY_HIGH = 1.00
NPC_WEAPONS_MAX_AIM_DELAY_HIGH = 1.50

NPC_WEAPONS_MIN_DROPOFF_DISTANCE_PISTOL = 512
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_PISTOL = 2048
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_SMG = 512
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_SMG = 2048
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_SHOTGUN = 256
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_SHOTGUN = 2048
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_RIFLE = 512
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_RIFLE = 4096
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_SNIPER = 1024
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_SNIPER = 8192

NPC_WEAPONS_SPREAD_MOVE_MULT_NONE = 1.0
NPC_WEAPONS_SPREAD_MOVE_MULT_LOW = 1.1
NPC_WEAPONS_SPREAD_MOVE_MULT_MED = 1.2
NPC_WEAPONS_SPREAD_MOVE_MULT_HIGH = 1.4
NPC_WEAPONS_SPREAD_MOVE_MULT_VHIGH = 5.0

NPC_WEAPONS_RELOAD_TIME_LOW = 1.8
NPC_WEAPONS_RELOAD_TIME_MED = 2.2
NPC_WEAPONS_RELOAD_TIME_HIGH = 2.6